version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  web:
    build: ./web
    container_name: agro-web
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - SQLITE_DB=/data/measurements.db
    volumes:
      - ./web/templates:/app/templates:ro
      - ./data_web:/data
    ports:
      - "5000:5000"
    restart: unless-stopped

  simulator:
    build: ./simulator
    container_name: simulator
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
    restart: "no"
